<a href="https://colab.research.google.com/github/joao-araujoo/calculo-numerico/blob/main/Atividade_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sistemas lineares e implementação numérica

**João Pedro Araujo e Rafael Augusto Guimarães**


## 1. Sistemas lineares na forma matricial

Para escrever um sistema linear na forma

$$
Ax=b,
$$
organizamos os coeficientes das incógnitas na matriz $A$, as incógnitas no vetor $x$ e os termos independentes no vetor $b$.

### a)

Sistema:

$$
\begin{cases}
2x+y=7\\
x-3y=-5
\end{cases}
$$
Logo,

$$
\begin{bmatrix}
2 & 1\\
1 & -3
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}
=
\begin{bmatrix}
7\\
-5
\end{bmatrix}.
$$
Portanto,

$$
A=
\begin{bmatrix}
2 & 1\\
1 & -3
\end{bmatrix},
\qquad
x=
\begin{bmatrix}
x\\
y
\end{bmatrix},
\qquad
b=
\begin{bmatrix}
7\\
-5
\end{bmatrix}.
$$
### b)

Sistema:

$$
\begin{cases}
x+2y-z=2\\
3x-y+2z=9\\
2x+y+z=7
\end{cases}
$$
Logo,

$$
\begin{bmatrix}
1 & 2 & -1\\
3 & -1 & 2\\
2 & 1 & 1
\end{bmatrix}
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix}
=
\begin{bmatrix}
2\\
9\\
7
\end{bmatrix}.
$$
Portanto,

$$
A=
\begin{bmatrix}
1 & 2 & -1\\
3 & -1 & 2\\
2 & 1 & 1
\end{bmatrix},
\qquad
x=
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix},
\qquad
b=
\begin{bmatrix}
2\\
9\\
7
\end{bmatrix}.
$$

## 2. Método da eliminação de Gauss

Sistema:

$$
\begin{cases}
2x+y-z=8\\
-3x-y+2z=-11\\
-2x+y+2z=-3
\end{cases}
$$
A matriz aumentada inicial é

$$
\left[
\begin{array}{ccc|c}
2 & 1 & -1 & 8\\
-3 & -1 & 2 & -11\\
-2 & 1 & 2 & -3
\end{array}
\right].
$$
Usando o primeiro pivô, fazemos

$$
L_2 \leftarrow L_2+\frac{3}{2}L_1
$$
e

$$
L_3 \leftarrow L_3+L_1.
$$
Assim,

$$
\left[
\begin{array}{ccc|c}
2 & 1 & -1 & 8\\
0 & \frac{1}{2} & \frac{1}{2} & 1\\
0 & 2 & 1 & 5
\end{array}
\right].
$$
Agora usamos o pivô da segunda linha. Para zerar o elemento abaixo dele:

$$
L_3 \leftarrow L_3-4L_2.
$$
Obtendo

$$
\left[
\begin{array}{ccc|c}
2 & 1 & -1 & 8\\
0 & \frac{1}{2} & \frac{1}{2} & 1\\
0 & 0 & -1 & 1
\end{array}
\right].
$$
### Substituição regressiva

Da terceira linha:

$$
-z=1
$$
$$
z=-1.
$$
Da segunda linha:

$$
\frac{1}{2}y+\frac{1}{2}z=1
$$
$$
\frac{1}{2}y-\frac{1}{2}=1
$$
$$
\frac{1}{2}y=\frac{3}{2}
$$
$$
y=3.
$$
Da primeira linha:

$$
2x+y-z=8
$$
$$
2x+3-(-1)=8
$$
$$
2x+4=8
$$
$$
x=2.
$$
Portanto,

$$
\boxed{x=2,\quad y=3,\quad z=-1}
$$

## 3. Número de soluções

### a)

$$
\begin{cases}
x+y=3\\
2x+2y=6
\end{cases}
$$
Matriz aumentada:

$$
\left[
\begin{array}{cc|c}
1 & 1 & 3\\
2 & 2 & 6
\end{array}
\right].
$$
Fazendo

$$
L_2 \leftarrow L_2-2L_1,
$$
temos

$$
\left[
\begin{array}{cc|c}
1 & 1 & 3\\
0 & 0 & 0
\end{array}
\right].
$$
A segunda equação é dependente da primeira. Há uma variável livre.

**Conclusão:** o sistema possui infinitas soluções.

---

### b)

$$
\begin{cases}
x+y=3\\
2x+2y=7
\end{cases}
$$
Matriz aumentada:

$$
\left[
\begin{array}{cc|c}
1 & 1 & 3\\
2 & 2 & 7
\end{array}
\right].
$$
Fazendo

$$
L_2 \leftarrow L_2-2L_1,
$$
obtemos

$$
\left[
\begin{array}{cc|c}
1 & 1 & 3\\
0 & 0 & 1
\end{array}
\right].
$$
A segunda linha representa

$$
0=1,
$$
o que é impossível.

**Conclusão:** o sistema não possui solução.

---

### c)

$$
\begin{cases}
x+y=3\\
2x-y=0
\end{cases}
$$
Matriz aumentada:

$$
\left[
\begin{array}{cc|c}
1 & 1 & 3\\
2 & -1 & 0
\end{array}
\right].
$$
Fazendo

$$
L_2 \leftarrow L_2-2L_1,
$$
temos

$$
\left[
\begin{array}{cc|c}
1 & 1 & 3\\
0 & -3 & -6
\end{array}
\right].
$$
Da segunda linha,

$$
-3y=-6 \Rightarrow y=2.
$$
Substituindo na primeira equação:

$$
x+2=3 \Rightarrow x=1.
$$
**Conclusão:** o sistema possui solução única,

$$
\boxed{x=1,\quad y=2}.
$$

## 4. Eliminação de Gauss em Python

A função abaixo implementa a eliminação de Gauss sem pivoteamento.

In [ ]:
import numpy as np

def gauss_sem_pivoteamento(A, b):
    """
    Resolve Ax = b usando eliminação de Gauss sem pivoteamento.

    Parâmetros
    ----------
    A : array_like
        Matriz quadrada dos coeficientes.
    b : array_like
        Vetor dos termos independentes.

    Retorno
    -------
    x : numpy.ndarray
        Vetor solução.
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)

    n = len(b)

    # Forma a matriz aumentada [A | b]
    M = np.hstack((A, b.reshape(-1, 1)))

    print("Matriz aumentada inicial:")
    print(M)

    # Eliminação progressiva
    for k in range(n - 1):
        if abs(M[k, k]) < 1e-12:
            raise ZeroDivisionError(
                f"Pivô nulo ou muito próximo de zero encontrado na linha {k + 1}."
            )

        for i in range(k + 1, n):
            multiplicador = M[i, k] / M[k, k]
            M[i, k:] = M[i, k:] - multiplicador * M[k, k:]

        print(f"\nApós a etapa {k + 1} da eliminação:")
        print(M)

    # Substituição regressiva
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        soma = np.dot(M[i, i + 1:n], x[i + 1:n])
        x[i] = (M[i, -1] - soma) / M[i, i]

    return x


# Sistema do exercício 2
A = np.array([
    [ 2,  1, -1],
    [-3, -1,  2],
    [-2,  1,  2]
], dtype=float)

b = np.array([8, -11, -3], dtype=float)

solucao_gauss = gauss_sem_pivoteamento(A, b)
solucao_numpy = np.linalg.solve(A, b)

print("\nSolução pelo algoritmo de Gauss:")
print(solucao_gauss)

print("\nSolução por numpy.linalg.solve:")
print(solucao_numpy)

print("\nAs soluções coincidem?")
print(np.allclose(solucao_gauss, solucao_numpy))

Matriz aumentada inicial:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Após a etapa 1 da eliminação:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

Após a etapa 2 da eliminação:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]

Solução pelo algoritmo de Gauss:
[ 2.  3. -1.]

Solução por numpy.linalg.solve:
[ 2.  3. -1.]

As soluções coincidem?
True


### Resultado e interpretação

O algoritmo fornece

$$
\boxed{x=2,\quad y=3,\quad z=-1}.
$$
O numpy.linalg.solve fornece o mesmo resultado. Portanto, a implementação da eliminação de Gauss está coerente com a solução obtida manualmente no exercício 2.

## 5. Modelo de balanço térmico

O sistema é

$$
\begin{bmatrix}
4 & -1 & 0\\
-1 & 4 & -1\\
0 & -1 & 3
\end{bmatrix}
\begin{bmatrix}
T_1\\
T_2\\
T_3
\end{bmatrix}
=
\begin{bmatrix}
15\\
10\\
10
\end{bmatrix}.
$$
Isso corresponde a

$$
\begin{cases}
4T_1-T_2=15\\
-T_1+4T_2-T_3=10\\
-T_2+3T_3=10
\end{cases}
$$
### a) Resolução manual

Das duas primeiras equações, podemos eliminar $T_1$. Multiplicando a segunda equação por 4:

$$
-4T_1+16T_2-4T_3=40.
$$
Somando com a primeira:

$$
4T_1-T_2=15,
$$
obtemos

$$
15T_2-4T_3=55.
$$
A terceira equação é

$$
-T_2+3T_3=10.
$$
Multiplicando-a por 15:

$$
-15T_2+45T_3=150.
$$
Somando com

$$
15T_2-4T_3=55,
$$
resulta em

$$
41T_3=205.
$$
Logo,

$$
T_3=5.
$$
Substituindo na terceira equação:

$$
-T_2+3(5)=10
$$
$$
-T_2+15=10
$$
$$
T_2=5.
$$
Substituindo na primeira equação:

$$
4T_1-5=15
$$
$$
4T_1=20
$$
$$
T_1=5.
$$
Portanto,

$$
\boxed{T_1=5,\quad T_2=5,\quad T_3=5}.
$$

### b) Solução em Python

In [ ]:
import numpy as np

A_termica = np.array([
    [ 4, -1,  0],
    [-1,  4, -1],
    [ 0, -1,  3]
], dtype=float)

b_termico = np.array([15, 10, 10], dtype=float)

T = np.linalg.solve(A_termica, b_termico)

print("Temperaturas calculadas:")
print(f"T1 = {T[0]:.6g}")
print(f"T2 = {T[1]:.6g}")
print(f"T3 = {T[2]:.6g}")

print("\nVerificação A @ T:")
print(A_termica @ T)

print("\nVetor b:")
print(b_termico)

Temperaturas calculadas:
T1 = 5
T2 = 5
T3 = 5

Verificação A @ T:
[15. 10. 10.]

Vetor b:
[15. 10. 10.]


### Interpretação

A solução numérica confirma a resolução manual:

$$
\boxed{T_1=T_2=T_3=5}.
$$
Ao calcular $A\cdot T$, recuperamos o vetor

$$
\begin{bmatrix}
15\\
10\\
10
\end{bmatrix},
$$
confirmando que os valores encontrados satisfazem o sistema de balanço térmico.